import {api,escape as e,number as n,minutes as mins,date,clubLink,playerLink,group,empty,card,table,tabs} from './ui.js';

const labels={goal:'But',shot:'Tir',save:'Arrêt du gardien',off_target:'Tir non cadré',yellow:'Carton jaune',red:'Carton rouge',substitution:'Remplacement',injury:'Blessure',kickoff:'Coup d’envoi',period_end:'Fin de période',forfeit:'Forfait',double_forfeit:'Double forfait',penalty_scored:'Tir au but réussi',penalty_missed:'Tir au but manqué',administrative_draw:'Qualification par tirage au sort'};
function pitch(lineup){const bands={GB:92,DC:75,DL:69,DR:69,MDC:59,MC:47,MOC:33,AILG:22,AILD:22,BU:14};const counts={};lineup.forEach(player=>counts[bands[player.position]]=(counts[bands[player.position]]||0)+1);const offsets={};return `<div class="pitch" aria-label="Composition initiale">${lineup.map(player=>{const y=bands[player.position]??45;const index=offsets[y]??0;offsets[y]=index+1;let x=(index+1)*100/(counts[y]+1);if(['DL','AILG'].includes(player.position))x=15;if(['DR','AILD'].includes(player.position))x=85;return `<${player.temporary?'span':'a'} ${player.temporary?'title="Joueur temporaire"':`href="#/player/${player.id}"`} class="pitch-player ${group(player.position)} ${player.temporary?'temporary-player':''}" style="left:${x}%;top:${y}%"><span class="shirt">${player.stats?.rating?n(player.stats.rating):player.position}</span><small>${e(player.name)}${player.temporary?' (temp.)':''}</small></${player.temporary?'span':'a'}>`;}).join('')}</div>`;}
export async function matchScreen(id,section){
 const match=await api(`/matches/${id}`);section=section||'summary';
 const header=`<section class="match-banner"><span class="eyebrow">${e(match.competition)} · ${e(match.round_label||`Journée ${match.round}`)}</span><div class="scoreboard"><div>${clubLink(match.home)}</div><div class="big-score">${match.score?match.score.join(' : '):'VS'}${match.penalties?`<small class="shootout-score">${match.penalties.join(' – ')} t.a.b.</small>`:''}</div><div>${clubLink(match.away)}</div></div><p>${date(match.date,true)} · ${match.neutral?'Terrain neutre':`${n(match.capacity)} places`} · ${match.result?'Terminé':'À venir'}</p></section>`;
 const result=match.result;
 if(!result)return header+card('Avant-match',empty('Cette rencontre sera simulée à sa date prévue.','Le coup d’envoi approche'));
 if(!result.home_stats)return header+card('Résultat archivé',empty('Le score est conservé. Les détails ne sont pas disponibles pour ce moteur ou cette saison archivée.','Score définitif'));
 let content='';
 if(section==='lineups')content=`<div class="grid equal">${['home','away'].map(side=>card(match[side].name,pitch(result[`${side}_lineup`])+table(['REMPLAÇANT','MIN.','NOTE'],result[`${side}_bench`].map(player=>[playerLink(player.id,player.name),player.stats?mins(player.stats.minutes):'—',player.stats?.rating?n(player.stats.rating):'—'])))).join('')}</div>`;
 else{
  const home=result.home_stats,away=result.away_stats;const totalPoss=home.possession_seconds+away.possession_seconds;
  const stats=[['Buts attendus (xG)',home.xg,away.xg],['Tirs',home.shots,away.shots],['Tirs cadrés',home.on_target,away.on_target],['Possession',100*home.possession_seconds/Math.max(1,totalPoss),100*away.possession_seconds/Math.max(1,totalPoss)],['Corners',home.corners,away.corners],['Coups francs',home.free_kicks,away.free_kicks],['Cartons jaunes',home.yellows,away.yellows],['Cartons rouges',home.reds,away.reds]];
  const comparisons=stats.map(([label,a,b])=>`<div class="comparison"><strong>${n(a)}${label==='Possession'?'%':''}</strong><div class="comparison-center">${label}<div class="comparison-bar"><span style="width:${a+b?a/(a+b)*100:50}%"></span><span style="width:${a+b?b/(a+b)*100:50}%"></span></div></div><strong>${n(b)}${label==='Possession'?'%':''}</strong></div>`).join('');
  const events=result.events.filter(event=>labels[event.kind] && (section==='timeline'||!['shot','save','off_target'].includes(event.kind)));
  const timeline=`<div class="timeline">${events.map(event=>`<div class="timeline-row"><span class="minute">${event.period===3?'TAB':`${Math.floor(event.second/60)}′`}</span><span class="event-icon">${({goal:'⚽',yellow:'▰',red:'▰',substitution:'⇄',injury:'✚',save:'◉'})[event.kind]||'•'}</span><div><strong class="${event.kind==='red'?'danger':''}">${labels[event.kind]}</strong>${event.period===3&&event.detail?` · ${e(event.detail)}`:''}${event.player?` · ${playerLink(event.player_id,event.player)}`:''}${event.kind==='substitution'&&event.secondary?` → ${playerLink(event.secondary_id,event.secondary)}`:''}<small>${e(event.team_id===match.home.id?match.home.name:match.away.name)}${event.xg!==null?` · xG ${n(event.xg)}`:''}</small></div></div>`).join('')}</div>`;
  content=`<div class="grid equal">${card('Le match en chiffres',`<div class="card-body">${comparisons}</div>`)}${card(section==='timeline'?'Chronologie complète':'Les temps forts',timeline)}</div>`;
 }
 return header+(result.status!=='played'?`<div class="notice">Résultat attribué par forfait (${e(result.status)}).</div>`:'')+tabs(`#/match/${id}`,[['summary','Compte rendu'],['lineups','Compositions'],['timeline','Chronologie']],section)+content;
}
