import {monthlySalary,salarySearchParams} from './salaries.js';
import {financialHistory,movementsHistory} from './club-history.js';
import {api,escape as e,number as n,minutes as mins,money,facilityRating,attributeScore,date,season,clubLink,playerLink,position,initials,form,empty,card,stat,fact,heading,tabs,table,pager,playerTable,standingsTable,seasonArchives,fixtures,transferTable,query,safeColor,contrastText} from './ui.js';

export async function dashboard(state,leagues){
 const featured=leagues[0];
 const [ranking,calendar,journal]=await Promise.all([api(`/competitions/${featured.id}/classement`),api(`/competitions/${featured.id}/calendrier`),api('/monde/journal')]);
 const hero=`<section class="hero"><div><span class="eyebrow">SAISON ${season(state.season)}</span><h2>Le football ne s’arrête jamais.</h2><p>Suivez les clubs, découvrez les talents et laissez chaque journée écrire la suite de l’histoire.</p></div><div class="hero-graphic" aria-hidden="true">${[[20,50],[40,20],[40,75],[65,40],[80,70],[85,15]].map(([x,y])=>`<i class="pitch-dot" style="left:${x}%;top:${y}%"></i>`).join('')}</div></section>`;
 const journalHtml=journal.items.length?journal.items.slice(0,9).map(item=>`<div class="journal-row"><span class="journal-icon">${({result:'⚽',transfer:'⇄',injury:'✚',season:'◇',academy:'↗'})[item.kind]||'•'}</span><div><p><a href="${item.match_id?`#/match/${item.match_id}`:item.player_id?`#/player/${item.player_id}`:'#/'}">${e(item.text)}</a></p><small>${date(item.date)}</small></div></div>`).join(''):empty('Faites avancer le temps pour voir les premiers événements.','Une nouvelle saison se prépare');
 return heading('LE MONDE DU FOOTBALL','Vue d’ensemble','Votre regard sur les cinq grands championnats.',`<span class="pill">● Univers synchronisé</span>`)+hero+`<div class="stat-grid">${stat('Clubs en compétition',n(state.active_clubs),'5 championnats européens')}${stat('Joueurs dans le monde',n(state.players),'Clubs actifs, dormants et libres')}${stat('Matchs disputés',n(state.played),`${n(state.fixtures)} au programme`)}${stat('Prochaine journée',new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date(`${state.next_match}T12:00:00`)),state.market?'Mercato ouvert':'Mercato fermé')}</div>`+`<div class="grid"><div>${card(featured.name,standingsTable({...ranking,items:ranking.items.slice(0,6)},true),`<a href="#/league/${featured.id}">Classement complet →</a>`)}${card(`Journée ${calendar.round}`,fixtures(calendar),`<a href="#/league/${featured.id}/calendar">Calendrier →</a>`)}</div><div>${card('Le journal du jour',journalHtml,`<a href="#/journal">Tout voir →</a>`)}</div></div><h2 class="section-title">Explorer les championnats</h2><div class="league-grid">${leagues.map(league=>`<a class="league-card" href="#/league/${league.id}"><span class="flag">${e(league.nation)}</span><h3>${e(league.name)}</h3><p>${league.clubs} clubs <span class="arrow">↗</span></p></a>`).join('')}</div>`;
}

export async function clubsScreen(params){
 const values={statut:'actif',tri:'reputation',...Object.fromEntries(params)};
 const data=await api(`/clubs?${query(values)}`);
 return heading('EXPLORER','Les clubs','Des grandes affiches aux talents du marché extérieur.')+`<form class="filters" data-filter><input type="search" name="recherche" value="${e(values.recherche)}" placeholder="Rechercher un club…" aria-label="Rechercher un club"><select name="statut" aria-label="Statut"><option value="actif" ${values.statut==='actif'?'selected':''}>Clubs actifs</option><option value="dormant" ${values.statut==='dormant'?'selected':''}>Clubs dormants</option></select><select name="tri" aria-label="Trier"><option value="nom" ${values.tri==='nom'?'selected':''}>Nom</option><option value="reputation" ${values.tri==='reputation'?'selected':''}>Réputation</option><option value="effectif" ${values.tri==='effectif'?'selected':''}>Effectif</option></select><button>Rechercher</button></form>`+card(`${n(data.total)} clubs`,table(['CLUB','PAYS','CHAMPIONNAT','RÉPUTATION','ENTRAÎNEMENT','RECRUTEMENT JEUNES','EFFECTIF','FORMATION'],data.items.map(club=>[`<span class="strong">${clubLink(club)}</span>`,e(club.nation),e(club.competition||'Marché extérieur'),`<span class="rating">${n(club.reputation)}</span>`,facilityRating(club.training_facilities),facilityRating(club.youth_recruitment),club.squad_size,e(club.formation)]))+pager(data));
}

export async function clubScreen(id,section,params){
 const club=await api(`/clubs/${id}`); section=section||'squad';
 const menu=[['squad','Effectif'],...(club.active?[['calendar','Calendrier']]:[]),['finances','Finances'],['transfers','Transferts'],...(club.active?[['history','Historique']]:[])];
 const major=safeColor(club.major_color), minor=safeColor(club.minor_color)||major;
 const crestStyle=major?` style="background:linear-gradient(155deg,${major} 55%,${minor} 55%);color:${contrastText(major)}"`:'';
 const title=`<div class="page-heading"><div class="identity"><div class="crest"${crestStyle}>${initials(club.name)}</div><div><span class="eyebrow">${e(club.nation)} · ${club.active?'CLUB ACTIF':'MARCHÉ EXTÉRIEUR'}</span><h1>${e(club.name)}</h1><p>${e(club.competition||'Club dormant')} · ${n(club.capacity)} places · ${e(club.formation)}</p><p class="club-facilities"><span title="TrainingFacilities : information uniquement, sans effet sur la simulation">Entraînement <b>${facilityRating(club.training_facilities)}</b></span><span title="YouthRecruitment : un meilleur recrutement augmente les chances de former des regens à fort potentiel">Recrutement des jeunes <b>${facilityRating(club.youth_recruitment)}</b></span></p></div></div>${club.standing?`<div><span class="pill">${club.standing.rank}${club.standing.rank===1?'er':'e'} · ${club.standing.points} points</span><p>${form(club.standing.form)}</p></div>`:''}</div>`;
 let content='';
 if(section==='squad'){const data=await api(`/clubs/${id}/effectif?${params}`); content=card(`Effectif · ${club.squad_size} joueurs`,playerTable(data,false,params.get('tri')||'rating',params.get('ordre')||'desc'),`<span class="legend">${['GB','DC','MC','BU'].map(position).join('')}</span>`);}
 else if(section==='calendar'){const data=await api(`/clubs/${id}/calendrier?${params}`); content=card('Calendrier de la saison',fixtures(data,true)+pager(data));}
 else if(section==='transfers'){const data=await api(`/clubs/${id}/transferts?${params}`);content=movementsHistory(data);}
 else if(section==='finances'){const data=await api(`/clubs/${id}/finances?${params}`); content=`<div class="stat-grid">${stat('Budget transferts',money(Math.max(0,data.transfer_budget-data.reserved_transfer_budget)),'Disponible hors offres en cours')}${stat('Solde',money(data.balance),'Trésorerie du club')}${stat('Revenus annuels',money(data.income),'Estimation structurelle')}${stat('Masse salariale',monthlySalary(data.wage_bill),'Par mois (moyenne)')}</div><div class="grid equal">${card('Engagements salariaux',`<div class="card-body">${fact('Masse salariale',monthlySalary(data.wage_bill)+' / mois')}${fact('Plafond',monthlySalary(data.wage_cap)+' / mois')}${fact('Offres en cours',monthlySalary(data.reserved_wages)+' / mois')}<div class="meter"><span style="width:${Math.min(100,100*data.wage_bill/Math.max(1,data.wage_cap))}%"></span></div><p>${Math.round(100*data.wage_bill/Math.max(1,data.wage_cap))}% du plafond utilisé</p></div>`)}${card('Activité de la saison',`<div class="card-body">${fact('Budget réservé aux offres',money(data.reserved_transfer_budget))}${fact('Achats',money(data.season_spent))}${fact('Ventes',money(data.season_sales))}${fact('Balance des transferts',money(data.season_sales-data.season_spent))}</div>`)}</div>`;content+=financialHistory(data.history);}
 else {const data=await api(`/clubs/${id}/historique?${params}`);content=card('Les saisons du club',table(['SAISON','CLASSEMENT','PALMARÈS'],data.items.map(row=>[season(row.season),`${row.rank}${row.rank===1?'er':'e'}`,row.champion?'✦ Champion':'—']))+pager(data))+seasonArchives(data);}
 return title+(!club.active?'<div class="notice">Club dormant : effectif et marché simulés, sans calendrier ni statistiques de match.</div>':'')+tabs(`#/club/${id}`,menu,section)+content;
}

export async function leagueScreen(id,section,params,leagues){
 const league=leagues.find(item=>item.id===Number(id)); if(!league)throw new Error('Championnat introuvable.');section=section||'table';
 let content='';
 if(section==='table'){const data=await api(`/competitions/${id}/classement?${params}`);content=card('Classement général',standingsTable(data),'<span class="muted">3 points pour une victoire</span>');}
 else if(section==='calendar'){const data=await api(`/competitions/${id}/calendrier?${params}`);content=card('Les rencontres',fixtures(data)+pager(data),`<form data-filter class="round-select"><select name="journee" aria-label="Journée">${data.rounds.map(round=>`<option value="${round}" ${data.round===round?'selected':''}>Journée ${round}</option>`).join('')}</select><button>Afficher</button></form>`);}
 else if(section==='stats'){const category=params.get('type')||'buteurs';const data=await api(`/competitions/${id}/statistiques?${query({...Object.fromEntries(params),type:category})}`);content=`<form class="filters" data-filter><select name="type" aria-label="Statistique">${[['buteurs','Meilleurs buteurs'],['passeurs','Meilleurs passeurs'],['notes','Meilleures notes'],['cartons','Cartons jaunes'],['clean_sheets','Clean sheets par club']].map(([key,label])=>`<option value="${key}" ${category===key?'selected':''}>${label}</option>`).join('')}</select><button>Afficher</button></form>`+card('Les leaders',table(['#',category==='clean_sheets'?'CLUB':'JOUEUR','CLUB','TOTAL'],data.items.map((row,index)=>[(data.page-1)*data.page_size+index+1,row.id?playerLink(row.id,row.name):clubLink(row.club),clubLink(row.club),`<b>${n(row.value)}</b>`]))+pager(data));}
 else{const data=await api(`/competitions/${id}/historique?${params}`);content=card('Le palmarès',table(['SAISON','CHAMPION','MEILLEUR BUTEUR','BUTS'],data.items.map(row=>[season(row.season),clubLink(row.champion),row.scorer?playerLink(row.scorer.id,row.scorer.name):'—',row.scorer?.value??'—']))+pager(data))+seasonArchives(data);}
 return heading(e(league.nation),league.name,`${league.clubs} clubs · Championnat aller-retour`)+tabs(`#/league/${id}`,[['table','Classement'],['calendar','Calendrier'],['stats','Statistiques'],['history','Historique']],section)+content;
}

export async function playersScreen(params){
 const data=await api(`/joueurs?${salarySearchParams(params)}`);const value=key=>e(params.get(key));
 const select=(key,label,items)=>`<select name="${key}" aria-label="${label}"><option value="">${label}</option>${items.map(([id,name])=>`<option value="${id}" ${params.get(key)===id?'selected':''}>${name}</option>`).join('')}</select>`;
 const filter=`<form data-filter><div class="filters"><input name="recherche" type="search" value="${value('recherche')}" placeholder="Rechercher un joueur…" aria-label="Rechercher un joueur">${select('poste','Tous les postes',['GB','DC','DL','DR','MDC','MC','MOC','AILG','AILD','BU'].map(role=>[role,role]))}${select('statut_club','Tous les clubs',[['actif','Clubs actifs'],['dormant','Clubs dormants']])}${select('contrat','Tous les contrats',[['libre','Agents libres'],['sous_contrat','Sous contrat']])}<button class="primary">Rechercher</button></div><details class="filters"><summary>Filtres avancés</summary><div class="filters"><label>Âge minimum <input name="age_min" type="number" min="0" max="100" value="${value('age_min')}"></label><label>Âge maximum <input name="age_max" type="number" min="0" max="100" value="${value('age_max')}"></label><label>Niveau minimum <input name="niveau_min" type="number" min="1" max="100" value="${value('niveau_min')}"></label><label>Nation (code) <input name="nation" value="${value('nation')}" placeholder="FRA"></label><label>Club (ID) <input name="club" type="number" value="${value('club')}"></label><label>Salaire min. (€/mois) <input name="salaire_min" type="number" min="0" value="${value('salaire_min')}"></label><label>Salaire max. (€/mois) <input name="salaire_max" type="number" min="0" value="${value('salaire_max')}"></label></div></details></form>`;
 return heading('LE VIVIER MONDIAL','Explorer les joueurs',`${n(data.total)} joueurs correspondent à votre recherche.`)+filter+card('Les joueurs',playerTable(data,true,params.get('tri')||'value',params.get('ordre')||'desc'));
}

const attributes={passe:'Passe',technique:'Technique',finition:'Finition',tacle:'Tacle',jeu_tete:'Jeu de tête',vision:'Vision',placement:'Placement',sang_froid:'Sang-froid',vitesse:'Vitesse',endurance:'Endurance',reflexes:'Réflexes',sorties:'Sorties',relance:'Relance'};
export async function playerScreen(id,section,params){
 const player=await api(`/joueurs/${id}`);section=section||'profile';
 const title=`<div class="page-heading"><div class="identity"><div class="avatar">${initials(player.name)}</div><div><span class="eyebrow">${player.retired?'CARRIÈRE ARCHIVÉE':e(player.nationalities.join(' · '))}</span><h1>${e(player.name)}</h1><p>${player.retired?'Retraité':`${position(player.position)} ${player.age} ans · ${clubLink(player.club)}`}</p></div></div>${player.rating?`<span class="rating">${n(player.rating)} / 100</span>`:''}</div>`;
 if(player.retired)section='history';
 let content='';
 if(section==='profile'){
  const estimate=player.potential_estimate;
  content=`<div class="stat-grid">${stat('Matchs',n(player.appearances),'Cette saison')}${stat('Buts',n(player.goals),`${n(player.assists)} passes décisives`)}${stat('Note moyenne',player.average?n(player.average):'—',`${mins(player.minutes)} minutes disputées`)}${stat('Valeur de marché',money(player.value),'Estimation')}</div><div class="grid"><div>${card('Les attributs · 1–20',`<div class="card-body"><div class="attributes-grid">${Object.entries(player.attributes).map(([key,value])=>`<div class="attribute"><span>${attributes[key]}</span><div class="meter"><span style="width:${attributeScore(value)*5}%"></span></div><strong>${attributeScore(value)}</strong></div>`).join('')}</div><p class="note">${player.attributes_imported?'Caractéristiques fournies dans le CSV, puis évoluant avec la simulation.':'Caractéristiques générées par la simulation ou une ancienne importation.'}</p></div>`)}${card('Identité et contrat',`<div class="card-body">${fact('Date de naissance',date(player.born))}${fact('Nationalité',e(player.nationalities.join(', ')))}${fact('Postes secondaires',player.secondary_positions.map(position).join(' ')||'—')}${fact('Club',clubLink(player.club))}${fact('Salaire mensuel',monthlySalary(player.wage))}${fact('Fin du contrat',date(player.contract_end))}</div>`)}</div><div>${card('Potentiel estimé',`<div class="card-body"><div class="potential">${Math.floor(estimate.lower)} – ${Math.ceil(estimate.upper)} <small>/ 100</small></div><p>Une fourchette d’observation, qui conserve une part d’incertitude.</p></div>`)}${Object.keys(player.position_ratings||{}).length?card('Aptitudes par poste · 1–20',`<div class="card-body position-ratings">${Object.entries(player.position_ratings).map(([role,score])=>fact(role,`<b>${score} / 20</b>`)).join('')}</div>`):''}${card('État du joueur',`<div class="card-body">${fact('Condition',`${Math.round(player.fitness*100)}%`)}<div class="meter"><span style="width:${player.fitness*100}%"></span></div>${fact('Forme',n(player.form))}${fact('Moral',`${Math.round(player.morale*100)}%`)}${fact('Blessure',player.injured_until?`<span class="danger">Retour le ${date(player.injured_until)}</span>`:'Disponible')}${player.discipline.map(item=>fact(item.competition,`${item.yellows} CJ · ${item.suspended_matches} match(s) de suspension`)).join('')}</div>`)}</div></div>`;
 }else{
  const data=await api(`/joueurs/${id}/historique?${params}`);const points=[...data.trajectory.items].reverse();
  const curve=points.length>1?`<svg class="trajectory" viewBox="0 0 600 180" role="img" aria-label="Évolution annuelle de la note"><path d="${points.map((point,index)=>`${index?'L':'M'}${25+index*550/(points.length-1)},${150-point.rating*1.3}`).join(' ')}" fill="none" stroke="#63864e" stroke-width="3"/>${points.map((point,index)=>`<circle cx="${25+index*550/(points.length-1)}" cy="${150-point.rating*1.3}" r="4" fill="#63864e"/><text x="${25+index*550/(points.length-1)}" y="173" text-anchor="middle" font-size="10" fill="#83917c">${point.season}</text>`).join('')}</svg>`:empty('La courbe se complète au bilan de chaque saison.');
  content=card('Évolution du niveau',curve)+card('La carrière',table(['SAISON','CLUB','COMPÉTITION','MATCHS','BUTS','PASSES','NOTE'],data.records.items.map(row=>[season(row.season),clubLink(row.club),e(row.competition),row.matches,row.goals,row.assists,row.average?n(row.average):'—']))+pager(data.records))+card('Parcours des transferts',transferTable(data.transfers));
 }
 return title+tabs(`#/player/${id}`,player.retired?[['history','Carrière']]:[['profile','Profil'],['history','Carrière']],section)+content;
}

export async function journalScreen(params){const data=await api(`/monde/journal?${params}`);return heading('AU FIL DES JOURS','Journal du monde','Résultats, mouvements et nouvelles des effectifs.')+`<form class="filters" data-filter><input type="date" name="date" value="${e(params.get('date'))}" aria-label="Date du journal"><button>Afficher</button></form>`+card('Les événements',table(['DATE','ÉVÉNEMENT'],data.items.map(item=>[date(item.date),`<a href="${item.match_id?`#/match/${item.match_id}`:item.player_id?`#/player/${item.player_id}`:'#/journal'}">${e(item.text)}</a>`]))+pager(data));}
